# Generated by Django 3.2.4 on 2021-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_mymodel_char_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='integer_field',
            field=models.IntegerField(null=True),
        ),
    ]
