# Generated by Django 3.2.4 on 2021-06-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_mymodel_integer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='date_field',
            field=models.DateField(null=True),
        ),
    ]
