# Generated by Django 3.2.4 on 2021-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_mymodel_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='datetime_field',
            field=models.DateTimeField(null=True),
        ),
    ]
